### ISSUE TITLE
Notes on Sunset Sample Video

### ISSUE THREAD

**Issue by mamund** [dret/HTTP-APIs#2]
- Maybe reverse face & slides (e.g. slides are most of the screen?)
 - At three minutes, seems we need to see the "motivation" slide (not continue w/ history)
 - Near the end maybe we can see the "references" or links slide ("hopefully this will encourage you to use this feature…."
 - End the video w/ the starting title slide (w/ link to the HTTP building Blocks site?)

**Comment by dret** [comment]
looks like all of this has been addressed by discussions and changes to the slide set.
